
# Write a program to accept a number from 1 to 7 and display the name of the day like 1 
# for Sunday , 2 for Monday and so on.

# a=int(input("Enter a number between 1 to 7"))
# if a==1:
#     print("Sunday")
# elif a==2:
#     print("Monday")
# elif a==3:
#     print("Tuesday")
# elif a==4:
#     print("Wednesday")
# elif a==5:
#     print("Thursday")
# elif a==6:
#     print("Friday")
# elif a==7:
#     print("saturady")
# else:
#     print("Invalid number")
